### PR TITLE
314 update v2 crowdsourcing forms

### LINKED ISSUE #314: Update V.2 Crowdsourcing Forms
**Is your feature request related to a problem? Please describe.**
Before the official launch for PHLASK 2.0, we would like to deploy the updated crowdsourcing forms that can be seen here: https://www.figma.com/file/l0lBzwPalGUg6JjcOXD2Xs/PHLASK--team-library?node-id=518%3A39607&t=lXQ0ULMfCqlCCvxo-1

**Describe the solution you'd like**
A user accessing PHLASK in a Desktop view experiences a design matching the one proposed for PHLASK 2.0. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Erw1nn**
# Pull Request

## Change Summary

Updated the AddBathroom, AddFood, AddForaging, and AddWaterTap components to match the Figma designs
https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&mode=design

## Change Reason

N/A

## Verification [Optional]

N/A

Related Issue: #314

### CODE REVIEW

**Comment by gcardonag** [comment]
Thanks for all the work you put into this so far! Based on what we talked about, here is some feedback for this MR:

- I'd recommend merging the develop branch back in to yours to address the merge conflicts. Just keep an eye out for what is clashing so that you don't lose any valuable work
- The current visual in the latest test site shows the submission form using the visual we use for mobile. We should definitely keep that but change how its shown so that it only appears on mobile.
- We should already have the initial view for adding a new resource on Desktop, but we may need to connect it so that shows up. I believe this was done in AddResourceModalV2. Once that is connected, it would be nice to have the form render like in this Figma sample: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=8303-149096&mode=design&t=qIrW9zRTGrNWioC8-4 (Totally recognize that this is a lot more scope, so only take this if you're up for it!)

**Comment by Erw1nn** [comment]
Quick update: 

So far I've addressed the merge conflicts and made it so the mobile form only appears on mobile. Going to work on getting the Desktop version of "Add Resource" to show on Desktop

**Comment by CmonUlot** [comment]
@tomporvaz  when should this be reviewed by the design circle?

**Comment by tomporvaz** [comment]
> @tomporvaz when should this be reviewed by the design circle?

@CmonUlot This doesn't appear to be working yet, but once the merge conflicts are resolved, and these changes are live on a testing site or beta site you should review it.

**Comment by Erw1nn** [comment]
This task is ready for a reviewer

**Comment by Erw1nn** [comment]
I've finished adding the desktop forms from @gcardonag 's feedback. I also migrated "AddResourceModal" to a functional component, mentioned in [#277](https://github.com/phlask/phlask-map/issues/277). This pull request is ready for another review

**Review by gcardonag — APPROVED** [review]
This looks so good, thank you for taking the time to work on this and the feedback throughout the PR 🙇

**Pull request merged**
