### PR TITLE
Basic work for GA

### PR DESCRIPTION
**Pull request by MihirDarji**
Added few GA events.

### CODE REVIEW

**Comment by keegan2149** [comment]
Hi Minhir, thanks for getting this done so quickly. You forgot to add the case structure that changes the GA tags based on the URL.

**Comment by gcardonag** [comment]
Just a heads up, the checks on this one will not fully work because we cannot deploy a test site from a fork-based PR. The check did confirm the site is building successfully.

**Comment by keegan2149** [comment]
> Just a heads up, the checks on this one will not fully work because we cannot deploy a test site from a fork-based PR. The check did confirm the site is building successfully.

Thanks. I'll merge it into a branch or something.

**Review by gcardonag — APPROVED** [review]

**Comment by gcardonag** [comment]
Thanks for the contribution @MihirDarji ! 🎉

**Pull request merged**
