### PR TITLE
Adding new subfolders and relevant files to the new "Utilities" folder.

### LINKED ISSUE #210: Develop an onboarding script
**Is your feature request related to a problem? Please describe.**
As a new developer, I would like to have a Python script that will print a greeting message whenever it is run. The greeting message should provide a warm welcome to whoever runs it and provide a list of useful links to places where someone new to the PHLASK project can learn more about:
- Our mission
- Our Development, Design, Data, and Civic circles
- What each circle is doing
- How to reach out to our team
- Our meeting rhythm
- Our technology stack

**Describe the solution you'd like**
A python script that prints a message with the items described above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by dibleauzah**
# Pull Request

## Change Summary

>> As we discussed before, I've added mainly three new assets: 
___1) The GH overview schema of our tech stack; this is what I'll use to curate and/or design the learning/review materials for all the relevant frameworks, libraries, APIs, DevOp- and source-control-related guides, etc. 
___2) Learning/review documentation for React; I'll add others, but I wanted for the conveners to first approve this; 
___3) And again, as I indicated before, the debugging-tips document (/"lessons-learned register," in PM-linguo).

## Change Reason
___Background: the relevant dev-circle members discussed the need for this utilities folder, with the discussion having evolved from the need for a Python greeting for new devs. 
___Resultant required action: I now need to implement the changes that I so promised, and which the conveners and group at large approved.

## Verification [Optional]
___N/A

Please see attached for the relevant screenshot.

Related Issue: #<Github Issue Number (if one exists)>
___#210; Link: https://github.com/phlask/phlask-map/issues/210

PHLAS-Utilities_Updates

### CODE REVIEW

**Review by RNR1 — CHANGES_REQUESTED** [review]
I think that "Utilities" might be a confusing name for this directory. Utilities, on a dev perspective usually refer to utility functions or reusable code helpers.
Maybe we should rename this directory to `docs` - so contextually it will be clear that we refer to a documentation

**Comment by dibleauzah** [comment]
@RNR1 Thanks. Gabe [ @gcardonag ], since that name was your idea, please advise.

/-----/
*Edit (added later): A quick additional comment for Ron [ @RNR1 ], as the rest of the ticket's discussion hasn't made this very clear.* 

To your point, that--housing "utility functions or reusable code helpers" assets in the sub-DIR--has been one of my intentions for it from the outset. And I believe Gabe is of the same view.

**Comment by dibleauzah** [comment]
@RNR1 & @gcardonag & fyi, @tomporvaz & @affabillyty A quick gentle check-in / reminder, folks. 
I know how overwhelming the Tuesday hack-night seshes often are for you, the conveners. So I just wanted to gently remind you of this PR. Per my response to you Ron, your concern is valid, but the purpose of the sub-DIR matches with what you're saying. IOW, the plan is for it to also house re-usable code scripts, etc., per your concern.

**Comment by affabillyty** [comment]
Hi all, I agree with Ron's recommendation if "Utilities" connotes something different among traditional development teams / environments. I would concur with changing it prior to it being merged.

@gcardonag if you have a counter-perspective on the name, please do share. Hopefully we can reach consensus so that this can be merged and Seif can work on the next step.

**Comment by dibleauzah** [comment]
@gcardonag Ola, hermano. You ok? Just a gentle reminder, re: this PR.

**Comment by gcardonag** [comment]
While I'm open to other ideas on the naming convention, the reason I went with "utilities" was because the intent for this task was to develop an onboarding script that can be run to welcome new joiners, potentially for new joiners to our #phlask_dev channel

**Comment by dibleauzah** [comment]
@gcardonag Please approve the PR when you get a chance, so I can continue with the ticket's work. I believe you've settled the issue of the sub-DIR's name.

**Review by gcardonag — APPROVED** [review]

**Comment by dibleauzah** [comment]
Thanks-a-mil, @gcardonag ! 🙏

**Comment by dibleauzah** [comment]
Thanks again, @gcardonag. I’m closing the PR now.

**Pull request closed without merging**
