### PR TITLE
322 update the wording on the phlask button on desktop

### LINKED ISSUE #322: Update the wording on the PHLASK Button on Desktop
**Is your feature request related to a problem? Please describe.**
Users can sometimes be confused around the purpose of the PHLASK text and what the button does. In response, we would like to change the PHLASK button text to "Near Me"

This would be an update to the Toolbar component.

**Describe the solution you'd like**
We would like the button to match the visual in this prototype: https://www.figma.com/proto/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?page-id=4510%3A29556&type=design&node-id=8105-140052&viewport=889%2C-851%2C0.09&scaling=scale-down&starting-point-node-id=8105%3A139899&show-proto-sidebar=1&mode=design 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jrsppf**
# Pull Request

## Change Summary

Created PhlaskButton.svg with 'Near Me' text and replaced 'PHLASK' button (phlaskWater.svg) in Toolbar.js component with PhlaskButton.svg.

## Change Reason

Users can sometimes be confused around the purpose of the PHLASK text and what the button does. In response, we would like to change the PHLASK button text to "Near Me" (https://github.com/phlask/phlask-map/issues/322).

## Verification [Optional]

Previous button text ('PHLASK')
322-screenshot_before_change

Updated button text ('Near Me')
322-screenshot_after_change

Related Issue: #322

### CODE REVIEW

**Comment by jrsppf** [comment]
@gcardonag I noticed in Logan's presentation from the Design Circle on 7/18 that most of the screenshots had the button labeled 'Nearest Me' instead of 'Near Me'. Is that something we can check on before reviewing this pull request?

**Review by IAmConnorWilson — APPROVED** [review]
nice!

**Comment by gcardonag** [comment]
> @gcardonag I noticed in Logan's presentation from the Design Circle on 7/18 that most of the screenshots had the button labeled 'Nearest Me' instead of 'Near Me'. Is that something we can check on before reviewing this pull request?

Good catch! I'll ask about this in the #phlask_design channel

**Review by gcardonag — APPROVED** [review]
The Design team confirmed that "Near Me" is the desired wording for this button. Thank you for submitting this change!

**Pull request merged**
