### PR TITLE
#245: Create PR Template

### LINKED ISSUE #245: Create PR Template
**Is your feature request related to a problem? Please describe.**

When creating PRs, there's no direction for the developer on what they should document and include in the PR. Create a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) for the repo so future developers will have direction when writing new PRs.

### PR DESCRIPTION
**Pull request by nwyin**
# Pull Request

## Change Summary

Creates PR template that will auto-populate PR body.

## Change Reason

- Make PR formatting more consistent
- Give contributors a template/checklist to follow...
- ...and (hopefully) making future PRs simpler easier to write

## Verification [Optional]

- Follow [official GitHub documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) for creating template PRs

Related Issue: #245

### CODE REVIEW

**Comment by nwyin** [comment]
s/o @edlopez000 for bringing up this idea.

**Review by gcardonag — COMMENTED** [review]
I like the idea of a PR template! Thanks @tnguyen21 and @edlopez000 !

Just thinking for folks newer to software development, do you have any recommendations for creating a .gif/video that we could include? For video, I'd think OBS is the best solution since it works across all platforms and is free to use. I'm not sure if there's an easy/free capture-to-gif option out there, but I've heard uploading an mp4 to imgur could work.

**Comment by nwyin** [comment]
@gcardonag Included a link to OBS in the PR template. I agree with your points that it's free and cross-platform. LMK if that looks good. Thanks!

**Review by gcardonag — APPROVED** [review]
This looks great! 🎉 Thanks for adding that note about OBS

**Review by edlopez000 — APPROVED** [review]

**Pull request merged**
